Update #187 add gender breakouts for employment variables
NeighborhoodInfoDC/ACS pull request #188
Opened 2022-07-21 21:23 UTC by maggiesu0725

2022-07-21 21:24 UTC, maggiesu0725 commented
@lhendey quite a lot of variables added, for review

2022-07-22 16:53 UTC, lhendey commented on Prog/SF_2015_19/ACS_2015_19_wv_sum_all.sas
> +%include "L:\SAS\Inc\StdLocal.sas";
need to get rid of this change. should be the sas1.

2022-07-22 18:00 UTC, lhendey commented on Macros/ACS_summary_geo_source_tr_vars.sas
> +      PopWorkFTLT75KB_M_&_years. =
These should be less than 75K not 75K+

2022-07-22 18:02 UTC, lhendey commented on Macros/ACS_summary_geo_source_tr_vars.sas
> +        %moe_sum( var=B20005Bm6, B20005Bm7, B20005Bm8, B20005Bm9, B20005Bm10, B20005Bm11,
should include e16 and e17?

2022-07-22 18:03 UTC, lhendey commented on Macros/ACS_summary_geo_source_tr_vars.sas
> +	  PopWorkFTLT35KB_M_&_years. =
these should income e16 & e17?

2022-07-22 18:04 UTC, lhendey commented on Macros/ACS_summary_geo_source_tr_vars.sas
> +	  PopWorkFTLT35KB_F_&_years. =
is less than 35K these should include e63 & e64

2022-07-22 18:06 UTC, lhendey requested changes
On both bg & tract file need to add gender to the full pop vars as well (line 220 for example on bg file)
Need to edit revisions statements when you run programs Acs_sf_2015_19_DC.sas, MD, WV, VA, etc. 
Need  PopInCivLaborForce to correctly calculate the unemployment rate.

2022-07-30 22:29 UTC, merged