ACS18-22 5yr Sum Tabs Issue #198
NeighborhoodInfoDC/ACS pull request #208
Opened 2024-02-02 06:03 UTC by RAGarMir

The ACS Sum Tabs for 18-22 are ready for review. @lhendey

2024-02-02 22:36 UTC, ptatian commented
Yes, I can review.

2024-02-02 22:41 UTC, ptatian commented
There seem to be a lot of updates to files that are not related to this update (in the Templates folder, for instance). I'm assuming that these are just mistakes, but please let me know if there was some reason these files were added/changed.

2024-02-02 23:06 UTC, RAGarMir commented
> There seem to be a lot of updates to files that are not related to this update (in the Templates folder, for instance). I'm assuming that these are just mistakes, but please let me know if there was some reason these files were added/changed.

I duplicated the templates folder to use the duplicate as my SF_XXXX_XX folder. I'm not sure if that registers as a change in both folders.

2024-02-02 23:18 UTC, ptatian requested changes
@RAGarMir The four programs for creating the ACS files look great! 

Yes, any files you copy or create with a .SAS extension are going to be tracked and will propagate through everyone's version of this repo. So we need to clean that up. Please delete your Template folder and the Acs_xxxx_yy_ss_sum_all.sas and SummaryFile_All_Macro.sas files from SF_2018_22. These changes will have to be committed and pushed to the remote repo. Only the four files for DC, MD, VA, and WV shoud be left in the pull request. Please let me know when that is done (or if you have questions) so that I can approve the changes before we merge this pull request. 

It's all part of the learning process. Thank you! cc: @lhendey

2024-02-02 23:22 UTC, ptatian commented on Prog/Template/Acs_sf_xxxx_yy_ss_remote.sas
@RAGarMir Sorry, noticing now that you moved this file from Templates to Templates. So, please don't delete this file but move it back to Templates.

2024-02-02 23:22 UTC, ptatian commented on Prog/SF_2018_22/SummaryFile_All_Macro.sas
@RAGarMir Same for this file. Please move it back to Templates.

2024-02-02 23:23 UTC, ptatian commented on Prog/SF_2018_22/ACS_xxxx_yy_ss_sum_all.sas
@RAGarMir Same for this file. Please move it back to Templates.

2024-02-02 23:25 UTC, ptatian commented on Prog/Template/Acs_sf_xxxx_yy_ss_remote.sas
Sorry, had to keep editing the above because I was mixing up Template and Templates. All of the template files you moved need to be put back in Templates (with an s). In the future, please copy template files...do not move them. Thanks!

2024-02-02 23:55 UTC, RAGarMir commented
@ptatian , The files are in the templates folder

2024-02-05 14:26 UTC, ptatian commented
Thanks, @RAGarMir. That looks good but we also need to remove the other two files in Prog\SF_2017_21. I probably should have explained this better. If you look at the [Files Changed tab](https://github.com/NeighborhoodInfoDC/ACS/pull/208) in the pull request, it will show you all of the changes between your update-#198 branch and the master branch. These are the changes that you are asking to push into the master branch. The only changes we should see are the four new programs you created for dowloading the ACS data: Acs_sf_2018_22_DC_remote.sas, Acs_sf_2018_22_MD_remote.sas, etc. No other changes are needed. 

Let me know if it would be helpful for @lhendey or me to walk through this with you. Thanks!

2024-02-06 14:54 UTC, ptatian commented
I'm sorry, @RAGarMir  In my previous comment I should have said "remove the other two files in **Prog\SF_2018_22**."

2024-02-06 17:41 UTC, RAGarMir commented
Hello, @ptatian. The files have been removed now.

2024-02-06 18:05 UTC, ptatian commented
Perfect!

2024-02-06 18:06 UTC, ptatian approved these changes
Code looks good. You can now proceed with the next steps.

2024-02-06 19:37 UTC, merged